name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install setuptools wheel twine

      - name: Update Version
        id: update_version
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const latest_release = data.tag_name;
            const release_number = parseInt(latest_release.slice(1)) + 1;
            console.log(release_number);
            return release_number;

      - name: Build
        run: |
          mkdir dist
          zip -r dist/Release.zip translations/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.update_version.outputs.result }}
          release_name: Release v${{ steps.update_version.outputs.result }}
          body: |
            This is release v${{ steps.update_version.outputs.result }} of my project.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/Release.zip
          asset_name: Release v${{ steps.update_version.outputs.result }}.zip
          asset_content_type: application/zip
